openapi: 3.0.0
info:
  title: Aspire APIs
  description: For the enterprise use
  version: 1.0.0
  contact:
    email: soham.patel@aspiresoftserv.in
servers:
  - url: http://localhost:3000
    description: Internal server for testing
paths:
  /:
    get:
      summary: Returns the root page.
      tags:
      - User API
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: return response string
          content:
            application/json:     
              schema:
                type: string
                example: "A Fake String"
  /users:
    get:
      summary: Returns the list of user.
      tags:
      - User API
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: return response string
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 12
                    Name:
                      type: string
                      example: username
                    favSinger:
                      type: string
                      example: singerName
                    song:
                      type: string
                      example: songName
    post:
      summary: Creates a user.
      tags:
      - User API
      responses:
        "201":
          description: Created

  /users/{userId}:
    get:
      summary: Returns a user by ID.
      tags:
      - User API
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 12
        "400":
          description: The specified user ID is invalid (not a number).
        "404":
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
    patch:
      summary: Update a user.
      tags:
      - User API
      responses:
        "200":
          description: Created

    delete:
      summary: Delete a user.
      tags:
      - User API
      responses:
        "200":
          description: Created
